pool:
  name: Default

resources:
  repositories:
    - repository: templates
      type: git
      name: ABIM.TFS.Build
      ref: main

steps:

- template: templates/dotnetframework.yml@templates
  parameters:
    BuildArgs: '$(Abim.OctopackMsbuildParams)'
    NugetProjectsList:
      - Abim.Enterprise.Core.Program.Interservice/Abim.Enterprise.Core.Program.Interservice.csproj
      - Abim.Enterprise.Core.Program.Resources/Abim.Enterprise.Core.Program.Resources.csproj
      - Abim.Platform.Program.Events/Abim.Platform.Program.Events.csproj
    TestAssemblies: '**\Release\*test*.dll'
    DotNetRestore: 'true'
